- name: Installing Istio
  become: yes
  shell: |
    cd /usr/local
    curl -L https://git.io/getLatestIstio |sh -
    echo "export PATH=\$PATH:/$(pwd)/$(ls -d istio*)/bin" >> /etc/profile
    cd $(ls -d istio*)
    kubectl apply -f install/kubernetes/istio.yaml
- name: Waiting Istio to be Ready
  become: yes
  shell: "kubectl get pod  --namespace=istio-system|grep istio-mixer"
  register: nodes
  until:      
    - '" Running "  in nodes.stdout'
  retries: 20
  delay: 5