- name: Enabling Epel
  become: yes
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: Installing Master Packages
  become: yes
  yum: pkg={{item}} state=latest
  with_items:
    - kubeadm-1.9.0
    - net-tools
    - kubectl-1.9.0
- name: Creating NSF Directory /nfs
  become: yes
  shell: |
    mkdir /nfs1
    chmod -R 777 /nfs1
    chown nfsnobody:nfsnobody /nfs1
    mkdir /nfs2
    chmod -R 777 /nfs2
    chown nfsnobody:nfsnobody /nfs2
    mkdir /nfs3
    chmod -R 777 /nfs3
    chown nfsnobody:nfsnobody /nfs3
    systemctl enable rpcbind
    systemctl enable nfs-server
    systemctl enable nfs-lock
    systemctl enable nfs-idmap
    systemctl restart rpcbind
    systemctl restart nfs-server
    systemctl restart nfs-lock
    systemctl restart nfs-idmap
    echo "/nfs1  *(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports
    echo "/nfs2  *(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports
    echo "/nfs3  *(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports
    systemctl restart nfs-server